services:
  - type: web
    name: agripool-app
    env: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: cookie
